route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'sns-notification'

receivers:
  - name: 'sns-notification'
    sns_configs:
      - topic_arn: 'SNS_arn'
        sigv4:
          region: eu-central-1
          profile: techstarter
          access_key: "xxxxx"
          secret_key: "xxxxx"

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal:
      - alertname
      - dev
      - instance






# route:
#   group_by: ['alertname']
#   group_wait: 30s
#   group_interval: 1m
#   repeat_interval: 1h
#   receiver: 'aws.sns'

# receivers:
#   - name: 'aws.sns'
#     sns_configs:
#     - sigv4:
#         region: eu-central-1
#       topic_arn: aws_sns_topic.prometheus-alerts.arn

# inhibit_rules:
#   - source_match:
#       severity: 'critical'
#     target_match:
#       severity: 'warning'
#     equal: ['alertname', 'dev', 'instance']

    