---
- name: Update system packages
  apt:
    update_cache: yes
    upgrade: dist  # Upgrade to the latest distribution packages

- name: Install Grafana package
  apt:
    name: grafana
    state: present


- name: copy grafana config file
  ansible.builtin.copy:
    src: files/grafana.ini
    dest: /etc/grafana/grafana.ini
    

- name: Start and enable Grafana service
  service:
    name: grafana-server
    state: started
    enabled: yes
  notify: Reload Grafana  # Notify to reload Grafana if the service is started or enabled
