
---
- name: Grafana & Prometheus
  hosts: prometheus
  roles: 
  - prometheus
  - grafana
  - alertmanager
  - node-exporter
  become: true



# - name: Prometheus Setup
#   hosts: prometheus
#   become: true
#   roles:
#     - prometheus

# - name: Node Exporter Setup
#   hosts: prometheus
#   become: true
#   roles:
#     - node-exporter

# - name: Grafana Setup
#   hosts: prometheus
#   become: true
#   roles:
#     - grafana

# - name: Deploy Prometheus and Alertmanager
#   hosts: prometheus
#   become: true
#   roles:
#     - prometheus
#     - alertmanager

